language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: ac-minesweeper
  api_key:
    secure: Ska10oPdyLQakSizBJ7AhrfrhQDww7e3SoNzDJFGI4icEO5i9QOwZj40kbXXek9xWyaeRkoTJEiJq0K/fTRXxSUQA1wcnzRGkdKyznZMC+JzAA1C03FUdblyx1WEenOZMcNt7Zs7nu+rnuAuhY2CEILVysEyeEmcDfe8aRoFahw2FqNu9h7txNaUHDO5sqbhBY57DAh9zYdBRN7OfpvRGurC6eeuv7XXgSjf8H+2Nhcwfal5uBjFzhfIHdbi2wZp2nLQnS5hsEw6Kl9e1MZ7lE/TRPWTOkuzDl03UQvNUoZiM9QafAxxvlLUqBS7HxgPYWfzW9pwBmq1fFQwf4lNW4t1WfjHQOPXk9Ocf4uNDaC2r8kKogBzzPLXhIHyGYTnusmB3aTNHWw4APMLigsBoDR1x5w1SOrg8GWxi4n6Bcy3u8mahZXXNDl6pLCNY8IZ0W1KhFJQwUXjjbTScCaWLRZFSJgu6bpsxVvNERVe1lQvsIvFrccdpK6ajLSoyGAsgzj1hQPY+vqQd/SbpOcRhMQpmwYE3C3OTYmpNrqpVDcXofCATXLAt72WISIMFF84UTtgyi/L8VEUt/klZUtIC1wCIf0Q4WH73LO6PYpOneeeP3k2M7PogUmw8qJNl2vK/hGPL+tn8PGnnCSxM9wkKhXf0QgN+AxzWIOoqKkdW0s=
